### ISSUE TITLE
Support for additional folders that should be covered

### ISSUE THREAD

**Issue by sloede** [julia-actions/julia-processcoverage#6]
In [Trixi.jl](https://github.com/trixi-framework/Trixi.jl) we store example setups that are used for testing in `examples/`, which lives outside the `src/` folder. To cover these files during coverage, we had to implement the coverage action manually in our CI (inspired by this very helpful action here!). However, I was wondering if it would be possible to add support for additional folders using the `with` syntax, such that one could do something like
```yaml
- uses: julia-actions/julia-processcoverage@v1
  with:
    additional-folders: examples, special_folder
```

The relevant section of our workflow file is here:
https://github.com/trixi-framework/Trixi.jl/blob/b4950a0fd8b8055fb99d846dea22276e3d408b07/.github/workflows/ci.yml#L91-L96
