### ISSUE TITLE
Set lcov file as output value

### ISSUE THREAD

**Issue by SaschaMann** [julia-actions/julia-processcoverage#9]
Rather than relying on convention, the action should return the resulting lcov file as an output. I don't expect people to change their existing setups, but in the long run

```yaml
      - uses: julia-actions/julia-processcoverage@v1
        id: coverage-processing
      - uses: codecov/codecov-action@v1
        with:
          file: ${{ steps.coverage-processing.outputs.lcov-file }}
```

seems less fragile than relying on `lcov.info`
